# docker-compose.yml
services:
  dev:
    build:
      context: .
      args:
        NODE_IMAGE: node:22.12-alpine
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "150"
    stdin_open: true
    tty: true
volumes:
  node_modules: